Repository WooGie911/Moving_BE, pull requests merged in 2025-08, with the labels that each got.

#205 [#197] test/notification 알림 기능 유닛 테스트 코드 추가.
  src/controllers/notification.controller.test.ts
  src/middlewares/notification.middleware.test.ts
  src/repositories/action.repository.test.ts
  src/repositories/notification.repository.test.ts
  src/services/action.service.test.ts
  src/services/notification.service.test.ts
Labels: 재욱, test, priority: low

#212 [#211]fix: 견적 요청, 일정 관리, 스키마&시드 수정
  src/controllers/estimateRequest.controller.ts
  src/db/prisma/migrations/20250801062303_add_name_optional/migration.sql
  src/db/prisma/schema.prisma
  src/db/prisma/seed-data/actions.json
  src/db/prisma/seed-data/estimate-requests.json
  src/db/prisma/seed-data/estimates.json
  src/db/prisma/seed-data/favorites.json
  src/db/prisma/seed-data/notifications.json
  src/db/prisma/seed-data/reviews.json
  src/db/prisma/seed.ts
  src/repositories/estimateRequest.repository.ts
  src/repositories/moverSchedule.repository.ts
  src/routes/estimateRequest.routes.ts
  src/routes/moverSchedule.routes.ts
  src/services/estimateRequest.service.ts
  src/services/moverSchedule.service.test.ts
  src/services/moverSchedule.service.ts
  src/types/moverSchedule.ts
  src/utils/dateUtils.ts
Labels: 승준, priority: critical, ready for review

#213 [#210] feat : 이름 유효성 검사에 중국어 추가 및 글자수 제한 설정
  src/services/auth.service.test.ts
  src/utils/validators/userValidator.ts
Labels: 민규, feat

#214 repactor: 유저 흐름에 맞는 필요 옵션 추가
  src/controllers/estimateRequest.controller.ts
  src/services/moverSchedule.service.ts
  src/types/moverSchedule.ts
  src/utils/addressUtils.ts
  src/utils/dateUtils.ts
  src/utils/scheduleUtils.ts
Labels: 승준, refactor, ready for review

#215 [#210] 유저 플로우 테스트 이슈 수정
  src/constants/profile.constants.ts
  src/middlewares/verifyToken.ts
  src/repositories/user.repository.ts
  src/services/user.service.test.ts
  src/services/user.service.ts
  src/utils/validators/profileValidator.ts
Labels: 민규, refactor, fix

#217 [#216] feat : 간편 로그인 전환에 필요한 반환값 추가
  src/controllers/auth.controller.ts
  src/repositories/user.repository.ts
  src/routes/auth.route.ts
  src/services/auth.service.ts
  src/services/user.service.ts
Labels: 민규, feat

#218 fix : 배포 상태에서 소셜 로그인후 역할 전환시 토큰 저장이 이상하던 문제 수정
  src/controllers/auth.controller.ts
  src/services/auth.service.ts
Labels: 민규, fix

#219 bug: career가 null일 경우 0으로 처리
  src/middlewares/translationMiddleware.ts
  src/repositories/mover.repository.ts
  src/services/translation.service.ts
Labels: 지연, fix

#220 feat : 소셜 로그인 계정으로 로컬 로그인시 에러 반환 추가
  src/repositories/auth.repository.ts
  src/services/auth.service.ts
  src/utils/validators/userValidator.ts
Labels: 민규, feat

#226 [#225] - 견적 : 플로우테스트 수정 및 유저기능 추가
  jest.config.js
  src/repositories/customerEstimateRequest.repository.ts
  src/repositories/moverEstimate.repository.ts
  src/routes/customerEstimateRequest.route.ts
  src/routes/moverEstimate.routes.ts
  src/services/customerEstimateRequest.service.test.ts
  src/services/customerEstimateRequest.service.ts
  src/services/translation.service.ts
Labels: 수빈, fix, feat

#227 fix : 소셜 로그인 계정으로 로컬 로그인시 에러 반환 수정
  src/services/auth.service.ts
Labels: 민규, fix

#228 HOTFIX: 단일 프리즈마 클라이언트 인스턴스 사용으로 트래픽 문제 해결
  src/db/prisma/prisma.ts
  src/repositories/auth.repository.ts
  src/repositories/customerEstimateRequest.repository.ts
  src/repositories/estimateRequest.repository.ts
  src/repositories/favorite.repository.ts
  src/repositories/mover.repository.ts
  src/repositories/moverEstimate.repository.ts
  src/repositories/moverSchedule.repository.ts
  src/repositories/review.repository.ts
  src/repositories/user.repository.ts
  src/services/expiration.service.ts
  src/types/customerEstimateRequest.ts
Labels: 승준, fix, priority: critical, ready for review

#231 chore/몰간,헬멧 적용
  package-lock.json
  package.json
  src/app.ts
Labels: 승준, chore, priority: critical

#233 [#230] feat : express-rate-limit 사용한 요청 제한 로직 미들웨어 구현
  package-lock.json
  package.json
  src/app.ts
  src/middlewares/rateLimiter.ts
  src/routes/auth.route.ts
  src/services/user.service.ts
  src/types/commonError.types.ts
  src/utils/handleError.ts
  src/utils/validators/profileValidator.ts
Labels: 민규, feat

#235 fix:견적 요청에서 proosed 상태의 견적만 관리, 스케줄 유틸에서 region과 city 둘 다 사용
  src/middlewares/translationMiddleware.ts
  src/repositories/estimateRequest.repository.ts
  src/utils/scheduleUtils.ts
Labels: 승준, fix, ready for review

#236 [#222] [#223] [#229] [알림] 알림 기능 관련 QA 피드백 반영 및 UX 개선.
  src/repositories/customerEstimateRequest.repository.ts
  src/repositories/estimateRequest.repository.ts
  src/repositories/review.repository.test.ts
  src/repositories/review.repository.ts
  src/services/customerEstimateRequest.service.ts
  src/services/mover.service.ts
  src/services/moverEstimate.service.ts
  src/services/notification.service.ts
  src/utils/actionNotificationMap.ts
  src/utils/scheduler.ts
Labels: 재욱, test, refactor, priority: medium

#238 [#221] [#237] [리뷰] dateUtil 함수 적용 및 동적데이터 다국어 기능 구현.
  src/controllers/review.controller.test.ts
  src/controllers/review.controller.ts
  src/routes/review.route.ts
  src/services/review.service.test.ts
  src/services/review.service.ts
Labels: 재욱, refactor, feat, chore, priority: medium

#240 [#239] [모니터링] 에러 추적을 위한 모니터링. sentry 추가.
  package-lock.json
  package.json
  src/app.ts
  src/instrument.ts
Labels: 재욱, priority: low, feat

#242 fix : 프로필 등록시 provider 값에따라 쿠키 저장 방식을 분기처리
  src/controllers/user.controller.ts
  src/services/user.service.ts
Labels: 민규, fix

#246 fix : 시나리오테스트 견적 - 유저 및 기사 오류수정
  src/services/customerEstimateRequest.service.ts
Labels: 수빈, refactor, fix

#249 [#248] test : auth 관련 테스트 코드 커버리지 개선 작업
  src/controllers/auth.controller.test.ts
  src/repositories/auth.repository.test.ts
  src/repositories/auth.repository.ts
Labels: 민규, test

#252 bug: 찜하기 중복 오류 해결
  src/controllers/favorite.controller.ts
  src/services/favorite.service.ts
Labels: 지연, fix

#253 [#250] [#251] [알림] 다국어 처리 및 유저 타입에 따른 알림 나눠 받기 처리.
  src/controllers/notification.controller.test.ts
  src/controllers/notification.controller.ts
  src/db/prisma/migrations/20250806023850_add_user_type_in_notification_and_action_type/migration.sql
  src/db/prisma/schema.prisma
  src/db/prisma/seed-data/actions.json
  src/db/prisma/seed-data/notifications.json
  src/db/prisma/seed.ts
  src/middlewares/notification.middleware.test.ts
  src/middlewares/notificationMiddleware.ts
  src/repositories/notification.repository.test.ts
  src/repositories/notification.repository.ts
  src/routes/notification.route.ts
  src/services/notification.service.test.ts
  src/services/notification.service.ts
  src/utils/actionNotificationMap.ts
Labels: 재욱, feat, priority: medium

#254 bug: 리뷰 필드명 수정
  src/services/mover.service.ts
  src/services/review.service.ts
Labels: 지연, fix

#255 Fix/favorite
  src/app.ts
  src/controllers/favorite.controller.ts
  src/repositories/favorite.repository.ts
  src/routes/favorite.routes.ts
  src/services/favorite.service.ts
Labels: 승준, fix, priority: high, ready for review

#261 fix:좋아요 API에 동적데이터 적용
  src/routes/favorite.routes.ts
Labels: 승준, fix, ready for review

#266 [#265]feat:모든 라우터에 CSRF 도입
  package-lock.json
  package.json
  src/controllers/auth.controller.ts
  src/controllers/favorite.controller.ts
  src/controllers/review.controller.ts
  src/controllers/user.controller.ts
  src/middlewares/csrfMiddleware.ts
  src/middlewares/errorMiddleware.ts
  src/middlewares/presignedUrl.ts
  src/middlewares/rateLimiter.ts
  src/routes/auth.route.ts
  src/routes/customerEstimateRequest.route.ts
  src/routes/estimateRequest.routes.ts
  src/routes/favorite.routes.ts
  src/routes/moverEstimate.routes.ts
  src/routes/review.route.ts
  src/routes/sse.route.ts
  src/routes/user.route.ts
  src/utils/handleError.ts
  src/utils/scheduler.ts
Labels: 승준, feat, priority: critical, ready for review

#269 기사님 찾기 관련 버그 수정
  src/repositories/mover.repository.ts
  src/repositories/review.repository.ts
  src/services/mover.service.ts
  src/services/review.service.ts
Labels: 지연, fix

#268 fix:라우터 미연결 상태, CSRF 미들웨어 구현
  src/routes/customerEstimateRequest.route.ts
  src/routes/moverEstimate.routes.ts
  src/routes/review.route.ts
  src/routes/user.route.ts
Labels: 승준, fix, priority: medium, ready for review

#276 [#275] test : user 유닛 테스트 작성
  src/controllers/user.controller.test.ts
  src/controllers/user.controller.ts
  src/repositories/user.repository.test.ts
Labels: 민규, test

#277 fix:CSRF 쿠키기반으로 변경하며 CORS 문제 해결
  src/app.ts
  src/middlewares/csrfMiddleware.ts
Labels: 승준, fix, ready for review

#281 feat: 기사님 프로필 수정 API에 CSRF 보안 미들웨어 적용
  src/routes/user.route.ts
Labels: 세준, refactor, priority: medium

#286 bug: 지정견적로직 재적용
  src/controllers/mover.controller.ts
  src/repositories/mover.repository.ts
  src/routes/mover.routes.ts
Labels: 지연, bug

#287 bug: 찜 조회에서 찜 갯수 조회 오류 해결
  src/repositories/favorite.repository.ts
  src/repositories/mover.repository.ts
Labels: 지연, bug

#296 bug: 스웨거 문법 오류 해결
  src/routes/mover.routes.ts
Labels: 지연, bug

#298 fix: 필드명 수정
  package-lock.json
  package.json
  src/repositories/mover.repository.ts
  src/services/mover.service.ts
Labels: 지연, fix

#309 [#305] [#306] [알림] [리뷰] redis를 적용한 API 캐싱 적용 및 테스트코드 수정.
  src/controllers/notification.controller.test.ts
  src/controllers/notification.controller.ts
  src/controllers/review.controller.ts
  src/middlewares/notification.middleware.test.ts
  src/repositories/notification.repository.test.ts
  src/repositories/review.repository.test.ts
  src/routes/notification.route.ts
  src/routes/review.route.ts
  src/services/notification.service.test.ts
  src/services/review.service.test.ts
  src/services/review.service.ts
  src/utils/actionNotificationMap.test.ts
  src/utils/emitNotificationSSE.test.ts
  src/utils/emitNotificationSSE.ts
Labels: 재욱, refactor, priority: high

#310 기사님 찾기 및 상세 통합테스트 & 스키마 필드 제거에 따른 필드 제거
  src/controllers/mover.controller.test.ts
  src/controllers/mover.controller.ts
  src/repositories/mover.repository.test.ts
  src/repositories/mover.repository.ts
  src/types/mover.types.ts
  tests/integration/moverDetail.int.test.ts
  tests/integration/moverSearch.int.test.ts
Labels: 지연, refactor, fix

#319 fix: 리뷰 캐싱 제거
  src/controllers/review.controller.ts
  src/repositories/mover.repository.test.ts
  src/routes/review.route.ts
  src/services/mover.service.test.ts
Labels: 지연, fix

#320 test: 견적요청 일정관리 찜하기 유닛테스트 커버리지 점수 높이기 및 미들웨어 테스트 코드 작성
  src/controllers/estimateRequest.controller.test.ts
  src/controllers/favorite.controller.test.ts
  src/middlewares/cacheMiddleware.test.ts
  src/middlewares/errorMiddleware.test.ts
  src/middlewares/translationMiddleware.test.ts
  src/repositories/estimateRequest.repository.test.ts
  src/repositories/favorite.repository.test.ts
  src/repositories/moverSchedule.repository.test.ts
  src/services/moverSchedule.service.test.ts
Labels: 승준, test, fix, feat, ready for review

#321 refactor : pw 변경 유효성 검사 로직 수정
  src/services/user.service.ts
Labels: 민규, refactor

#322 [리뷰] [알림] 리뷰 캐싱 무효화 로직 변경 및 테스트 커버리지 증가.
  src/controllers/notification.controller.test.ts
  src/controllers/review.controller.test.ts
  src/controllers/review.controller.ts
  src/middlewares/cacheMiddleware.ts
  src/middlewares/notification.middleware.test.ts
  src/middlewares/review.middleware.test.ts
  src/services/review.service.test.ts
Labels: 재욱, refactor, priority: low

#330 chore : 배포 오류로인한 재푸쉬
  tests/integration/auth.int.test.ts
Labels: 민규

#334 [#333] 견적- 공유하기 API 작성
  src/controllers/share.controller.test.ts
  src/controllers/share.controller.ts
  src/repositories/share.repository.test.ts
  src/repositories/share.repository.ts
  src/routes/index.routes.ts
  src/routes/share.route.ts
  src/services/share.service.test.ts
  src/services/share.service.ts
Labels: 수빈, refactor, feat

#332 [리뷰] [알림] API 캐싱 제거 및 테스트 커버리지 증가.
  src/controllers/notification.controller.test.ts
  src/controllers/notification.controller.ts
  src/controllers/review.controller.test.ts
  src/controllers/review.controller.ts
  src/middlewares/cacheMiddleware.ts
  src/middlewares/notification.middleware.test.ts
  src/middlewares/review.middleware.test.ts
  src/routes/notification.route.ts
  src/routes/review.route.ts
  src/services/review.service.test.ts
Labels: 재욱, test, refactor, priority: low, fix

#336 fix:좋아요 캐싱 제거
  src/controllers/favorite.controller.test.ts
  src/controllers/favorite.controller.ts
  src/routes/favorite.routes.ts
  src/routes/mover.routes.ts
Labels: 승준, fix, ready for review

#338 [#337] bug: 기사님 찾기 null값 0으로 처리
  src/repositories/mover.repository.test.ts
  src/repositories/mover.repository.ts
Labels: 지연, fix

#339 refacotr : ux 향상을 위한 late-limit 속성값 조절
  src/middlewares/rateLimiter.ts
Labels: 민규, feat

#340 feat: API 캐싱 적용
  src/routes/user.route.ts
Labels: 세준, feat, priority: medium

#341 fix: 견적 요청에서 기사님 견적서를 반려했을 때 캐싱 무효화 적용
  src/routes/customerEstimateRequest.route.ts
Labels: 승준, fix, ready for review

#342 [알림] hotfix: 디버깅용 에러 콘솔로그 추가.
  src/middlewares/notificationMiddleware.ts
  src/routes/sse.route.ts
  src/utils/emitNotificationSSE.ts
Labels: 재욱, priority: high, bug

#344 [알림] hotfix: 로드밸런서 관련 디버깅 코드 추가.
  src/routes/sse.route.ts
  src/utils/emitNotificationSSE.ts
Labels: 재욱, fix, priority: critical

#345 fix:일정관리 캐싱 및 번역 문제 해결
  src/middlewares/translationMiddleware.ts
  src/routes/moverSchedule.routes.ts
  src/utils/scheduleUtils.ts
Labels: 승준, fix, ready for review

#347 bug: mover.service 유닛테스트 타임 아웃 문제 해결
  src/services/mover.service.test.ts
Labels: 지연, bug

#348 Fix : 견적-기사 서비스레이어 테스트코드 타입에러 수정
  src/routes/customerEstimateRequest.route.ts
  src/services/moverEstimate.service.test.ts
  src/services/moverMyPage.service.test.ts
Labels: 수빈, fix

#349 fix : 테스트 코드 오류 수정
  src/controllers/auth.controller.test.ts
  src/services/auth.service.ts
  src/services/user.service.test.ts
  src/services/user.service.ts
Labels: 민규, test

#350 fix: 다국어 미들웨어 테스트 코드 fail 해결
  src/services/translation.service.test.ts
  src/services/translation.service.ts
Labels: 승준, test, fix

#351 [알림] Hotfix/noti SSE 연결 관련 디버깅.
  src/routes/sse.route.ts
  src/services/notification.service.ts
  src/utils/emitNotificationSSE.ts
Labels: 재욱, priority: critical, bug

#367 fix: 디버깅을 위해 사용했던 로그 삭제(최소화)
  src/controllers/estimateRequest.controller.test.ts
  src/controllers/favorite.controller.ts
  src/middlewares/cacheMiddleware.ts
  src/middlewares/translationMiddleware.ts
  src/services/expiration.service.ts
  src/services/translation.service.ts
  src/utils/redisClient.ts
  src/utils/scheduler.ts
Labels: 승준, ready for review

#370 지정견적 캐시무효화
  src/routes/customerEstimateRequest.route.ts
  src/routes/mover.routes.ts
  src/routes/moverEstimate.routes.ts
Labels: feat

#371 [#369] dev에서 main으로 default 브랜치 변경.
  .github/workflows/deploy.yml
Labels: 재욱, chore, priority: critical
